#!/usr/bin/env perl
# Copyright 2020 David Neto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use Data::Dumper;

# (x,y) cartesian position of the ship
# direction east is 0.
my ($x, $y, $dir) = (0,0,0);
my @insts = map { chomp; $_ } (<>);
print Dumper(\@insts);

foreach my $inst (@insts) {
  if ($inst =~ m/^N(\d+)/) {
    $y += $1;
  } elsif ($inst =~ m/^S(\d+)/) {
    $y -= $1;
  } elsif ($inst =~ m/^E(\d+)/) {
    $x += $1;
  } elsif ($inst =~ m/^W(\d+)/) {
    $x -= $1;
  } elsif ($inst =~ m/^L(\d+)/) {
    $dir = ($dir + $1) % 360;
  } elsif ($inst =~ m/^R(\d+)/) {
    $dir = ($dir - $1) % 360;
  } elsif ($inst =~ m/^F(\d+)/) {
    if ($dir == 0) {
      $x += $1;
    } elsif ($dir == 90) {
      $y += $1;
    } elsif ($dir == 180) {
      $x -= $1;
    } elsif ($dir == 270) {
      $y -= $1;
    }
  }
}

my $manh = abs($x) + abs($y);
print "Position ($x,$y) or Manhattan $manh units\n";
