#!/usr/bin/env perl
# Copyright 2020 David Neto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use Data::Dumper;

# Key is rule number. Value is an object which is one of the
# rule classes below: Char, Sequence, Alternate.
my %rule = ();

my $indent = 1;
sub indent() { return ' ' x $indent; }

package Char;
sub new($$$) {
  my ($class,$i,$char) = @_;
  my $self = [$i,$char];
  bless $self, $class;
  return $self;
}
# Matches suffix of a string.
# Returns a pair:
#   0, string: failed match, and remaining prefix
#   1, string: successful match, and remaining prefix
sub match($$$) {
  my ($self,$str,$ignored) = @_;
  my ($i,$char) = @$self;
  if ($str =~ m/(.*)(.)$/) {
    my ($prefix,$last) = ($1,$2);
    if ($last eq $char) {
      print ::indent(), "$i:Char->1 $char $last\n";
      return (1, $prefix);
    }
  }
  print ::indent(), "$i:Char->0 $char $str\n";
  return (0, $str);
}

package Sequence;
sub new($$@) {
  # The parts are numbers of some other rules.
  my ($class,$i,@parts) = @_;
  my $self = [$i,@parts];
  bless $self, $class;
  return $self;
}

sub match($$$) {
  my ($self,$str,$count) = @_;
  my ($i,@parts) = @$self;
  my $ok;
  my $prefix = $str;
  print ::indent(), "$i:Seq[$count] $str\n"; $indent++;
  foreach my $part (reverse @parts) {
    ($ok, $prefix) = $rule{$part}->match($prefix,$count);
    unless ($ok) {
      $indent--; print ::indent(), "$i:Seq[$count]->0 $str\n";
    }
    return (0, $str) unless $ok;
  }
  $indent--; print ::indent(), "$i:Seq[$count]->1 $prefix\n";
  return (1, $prefix);
}

package Alternate;
sub new($$@) {
  # The parts are other rules, or the numbers naming those other rules.
  my ($class,$i,@parts) = @_;
  my $self = [$i,@parts];
  bless $self, $class;
  return $self;
}
sub match($$$) {
  my ($self,$str,$ignored) = @_;
  my ($i,@parts) = @$self;
  print ::indent(), "$i:Alt $str\n"; $indent++;
  foreach my $part (@parts) {
    my $subrule = (ref $part ? $part : $rule{$part});
    my ($ok, $prefix) = $subrule->match($str,1);
    if ($ok) {
      $indent--; print ::indent(), "$i:Alt->1 $prefix\n";
    }
    return (1, $prefix) if $ok;
  }
  $indent--; print ::indent(), "$i:Alt->0 $str\n";
  return 0, $str;
}

package OneOrMore;
sub new($$$) {
  # An expression of one or more times a subpart.
  my ($class,$i,$subpart) = @_;
  my $self = [$i,$subpart];
  bless $self, $class;
  return $self;
}
sub match($$$) {
  my ($self,$str,$count) = @_;
  my ($i,$subrule) = @$self;
  my $num_matched = 0;
  my $ok;
  my $prefix = $str;
  print ::indent(), "$i:OneOrMore($count) $str\n"; $indent++;
  do {
    ($ok, $prefix) = $rule{$subrule}->match($prefix,$count);
    if ($ok) {
      print ::indent(), "$i:OneOrMore($count) + $prefix\n";
    }
    $num_matched++ if $ok;
  } while($ok);
  if ($num_matched) {
    $indent--; print ::indent(), "$i:OneOrMore($count)->1 $prefix\n";
    return 1, $prefix;
  }
  $indent--; print ::indent(), "$i:OneOrMore($count)->0 $str\n";
  return 0, $str;
}

package EqualCount;
sub new($$$$) {
  # An expression of an equal number of As then Bs.
  my ($class,$i,$a,$b) = @_;
  my $self = [$i,$a,$b];
  bless $self, $class;
  return $self;
}
sub match($$$) {
  # Returns status, number-successful_b, remaining
  my ($self,$str,$count) = @_;
  my ($i,$b,$a) = @{$self};
  my $num_a = 0;
  my $num_b = 0;

  print ::indent(), "$i:EqualCount[$count] $str\n"; $indent++;

  my $ok;
  my $prefix = $str;
  do {
    ($ok, $prefix) = $rule{$a}->match($prefix,$count);
    $num_a++ if $ok;
    if ($ok) {
      print ::indent(), "$i:EqualCount[$count] a:$num_a $prefix\n";
    }
  } while($ok);
  return (0, $str) unless $num_a;
  do {
    ($ok, $prefix) = $rule{$b}->match($prefix,$count);
    $num_b++ if $ok;
    if ($ok) {
      print ::indent(), "$i:EqualCount[$count] a:$num_a b:$num_b $prefix\n";
    }
  } while($ok and ($num_a > $num_b));
  if ($num_a == $num_b) {
    $indent--; print ::indent(), "$i:EqualCount[$count]->1 a:$num_a b:$num_b $prefix\n";
    return 1, $prefix;
  } else {
    $indent--; print ::indent(), "$i:EqualCount[$count]->0 a:$num_a b:$num_b $str\n";
    return 0, $str;
  }
}

package main;

my @strings = ();
my $in_strings;
foreach my $line (<>) {
  chomp $line;
  if ($line =~ m/^(\d+):\s*"(.)"/) {
    $rule{$1+0} = new Char($1+0,$2);
  } elsif ($line =~ m/^(\d+):\s+(\d+)\s+(\d+)\s+\|\s+(\d+)\s+(\d+)$/) {
    my ($i,$a,$b,$c,$d) = map {$_+0;} ($1,$2,$3,$4,$5);
    $rule{$i} = new Alternate($i,
                   new Sequence($i,$a,$b),
                   new Sequence($i,$c,$d));
  } elsif ($line =~ m/^(\d+):\s+(\d+)\s+\|\s+(\d+)$/) {
    my ($i,$a,$b) = map {$_+0;} ($1,$2,$3);
    $rule{$i} = new Alternate($i,$a,$b);
  } elsif ($line =~ m/^(\d+):\s+(\d+)\s+\|\s+(\d+)\s+(\d+)$/) {
    my ($i,$a,$b,$c) = map {$_+0;} ($1,$2,$3,$4);
    ($a == $b) or die "Expected $a == $b in: $line\n";
    ($i == $c) or die "Expected $i == $c in: $line\n";
    $rule{$i} = new OneOrMore($i,$a);
  } elsif ($line =~ m/^(\d+):\s+(\d+)\s+(\d+)\s+\|\s+(\d+)\s+(\d+)\s+(\d+)$/) {
    my ($i,$a,$b,$c,$d,$e) = map {$_+0;} ($1,$2,$3,$4,$5,$6);
    ($a == $c) or die "Expected $a == $c in: $line\n";
    ($b == $e) or die "Expected $b == $e in: $line\n";
    ($i == $d) or die "Expected $i == $d in: $line\n";
    $rule{$i} = new EqualCount($i,$a,$b);
  } elsif ($line =~ m/^(\d+):\s+(\d+)\s+(\d+)$/) {
    my ($i,$a,$b) = map {$_+0;} ($1,$2,$3);
    $rule{$i} = new Sequence($i,$a,$b);
  } elsif ($line =~ m/^(\d+):\s+(\d+)$/) {
    my ($i,$a) = map {$_+0;} ($1,$2);
    $rule{$i} = new Sequence($i,$a);
  } elsif ($line =~ m/^\s*$/) {
    $in_strings = 1;
  } elsif ($in_strings and $line =~ m/.+/) {
    push @strings, $line;
  } else {
    die "unerecognized line: $line\n";
  }
}

print Dumper(\%rule);
print Dumper(\@strings);
print "\n";

sub matched($) {
  my $str = shift;
  my ($ok, $remain) = $rule{0}->match($str,1);
  return (($ok == 1) and ($remain eq ''));
}

my $num = 0;
foreach my $str (@strings) {
  $indent = 1;
  print "$str -> \n";
  if (matched($str)) {
    $num++;
    print "YEA $str\n";
  } else {
    print "NO  $str\n";
  }
}
print "\n$num matched\n";

