#!/usr/bin/env perl
# Copyright 2020 David Neto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;

my @grid = (map {chomp; $_} (<>));

sub num_trees_for_slope($$) {
  my ($step_x, $step_y) = @_;
  my $x = 0;
  my $y = 0;
  my $num_trees = 0;
  while ($y <= $#grid) {
    my $landed = substr($grid[$y], ($x % length $grid[$y]), 1);
    $num_trees++ if $landed eq '#';
    $x += $step_x;
    $y += $step_y;
  }
  return $num_trees;
}

my @slopes = ([1,1], [3,1], [5,1], [7,1], [1,2]);

my $product = 1;
foreach my $pair (@slopes) {
  my $n = num_trees_for_slope(${$pair}[0], ${$pair}[1]);
  $product = $product * $n;
}

print "$product\n";
exit 0;
