#!/usr/bin/env perl
# Copyright 2020 David Neto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use Data::Dumper;

my ($arrival,$buslist) = map {chomp; $_} (<>);
my $arrival = 0 + $arrival;
my @bus = map { 0+$_; } (grep {/\d+/} (split(/,/,$buslist)));

print Dumper($arrival, \@bus);

my $min_wait = 1e10;
my $best_bus = undef;
foreach my $bus (@bus) {
  my $late_by = $arrival % $bus;
  my $wait = ($late_by == 0) ? 0 : ($bus - $late_by);
  ($best_bus, $min_wait) = ($bus,$wait) if $wait < $min_wait;
}
print "Best bus is $best_bus, waiting $min_wait\n";
print "Answer ", ($best_bus * $min_wait), "\n";
