#!/usr/bin/env perl
# Copyright 2020 David Neto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use Data::Dumper;

my ($arrival,$buslist) = map {chomp; $_} (<>);
my $arrival = 0 + $arrival;
my @bus = split(/,/,$buslist);

print Dumper($arrival, \@bus);

my $num_solved = 0;
my $step = 1;  # Product of step sizes of solved buses.
my $i = 0;
while ($num_solved <= $#bus) {
  print "$num_solved $i\n";
  if ($bus[$num_solved] eq 'x') {
    $num_solved++;
  } else {
    if ((($i + $num_solved) % $bus[$num_solved]) == 0) {
      $step = $step * $bus[$num_solved];
      $num_solved++;
    } else {
      $i += $step;
    }
  }
}
print "Answer $i\n";
