#!/usr/bin/env perl
# Copyright 2020 David Neto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;

# Key is the number, value is the highest index to have that number, except
# for the very last entry in in @num.
my %last = ();
my @num = ();

# Assume input is one number per line.
my (@num) = map { 0+ $_; } (<>);
foreach my $i (0..$#num - 1) {
  $last{$num[$i]} = $i;
}
while ($#num < 29999999) {
  my $prev = $last{$num[$#num]};

  my $next_entry = 0;
  $next_entry = ($#num - $prev) if defined $prev;
  $last{$num[$#num]} = $#num;
  push @num, $next_entry;
}

print $num[$#num],"\n";
