#!/usr/bin/env perl
# Copyright 2020 David Neto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;

my $num_valid = 0;
foreach my $line (<>) {
  if ($line =~ m/^(\d+)-(\d+)\s+(\w):\s+(\w*)/) {
    my ($first,$second,$letter,$word) = ($1,$2,$3,$4);
    my @letters = split(//,$word);
    my $match0 = ($letters[$first-1] eq $letter);
    my $match1 = ($letters[$second-1] eq $letter);
    $num_valid++ if ($match0 != $match1);
  }
}
print "$num_valid\n";
exit 0;
